export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  tags?: ("new" | "fix" | "polish" | "feature" | "balance")[];
  items: string[];
}

export const CURRENT_VERSION = "5.7.2";

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "5.7.2",
    date: "2026-06",
    title: "Admin Ops + Feedback Inbox + App Version Control",
    tags: ["new", "feature", "polish"],
    items: [
      "Protected /admin route added for internal Streex operations",
      "Admin access foundation added with server-side validation through the admin-ops Edge Function",
      "Initial owner admin seeded for juangaudino@gmail.com through the admin_users table",
      "User management tools added for totals, recent users, inactive users, blocked users, usage stats, and account restriction actions",
      "Block/unblock support added through account_access_controls with a restricted-account screen on app load",
      "Delete user action is intentionally implemented as delete_pending soft restriction instead of destructive data deletion",
      "Force Sign Out All Users added as an app-level forced_logout_after timestamp checked during auth/runtime load",
      "App version control added with optional or required update notices and a Refresh App action",
      "Suggestions / Feedback added to the Avatar menu with suggestion, bug report, and general feedback types",
      "Admin Feedback Inbox added for filtering, reviewing, planning, resolving, dismissing, or deleting feedback",
      "No dashboard, earnings, XP, Ask My Data, exports, themes, or Supabase project architecture changes were made",
    ],
  },
  {
    version: "5.7.1",
    date: "2026-06",
    title: "Navigation Cleanup + AI Visibility Layer",
    tags: ["polish"],
    items: [
      "Ask AI is now promoted to the primary bottom navigation for stronger Ask My Data visibility",
      "Compare moved from the bottom navigation into the Progress menu",
      "History moved from the Avatar menu into the Progress menu",
      "Progress menu now groups Journey, Monthly Recap, Letters, Achievements, History, and Compare",
      "Avatar menu simplified to Settings, What's New, and Sign Out",
      "No routes, dashboard logic, auth, earnings, XP, analytics, or backend behavior were changed",
    ],
  },
  {
    version: "5.7",
    date: "2026-05",
    title: "Full Focus Dashboard",
    tags: ["new", "feature", "polish"],
    items: [
      "Full Focus Dashboard Experience added as an operational mode separate from themes",
      "Settings now includes Dashboard Experience with Standard and Full Focus options",
      "Dashboard includes a compact quick toggle for switching between Standard and Full Focus",
      "Full Focus prioritizes current earnings, same-day average comparison, goal progress, shift state, momentum, and Quick Add",
      "Weather, traffic, historical day context, and momentum remain available as calmer secondary operational context",
      "Driver Identity, achievements, milestones, and longer reflection systems stay in Standard instead of dominating Full Focus",
      "Header and navigation quiet slightly in Full Focus to reclaim vertical space",
      "Dashboard mode toggle now lives in the top app header near Progress and Profile controls with the current mode clearly visible",
      "Full Focus now uses a tighter driver-console layout with Quick Add immediately after the cockpit summary",
      "Daily Command Center renders as a compact utility strip in Full Focus so live utility no longer dominates the top of the dashboard",
      "Start Shift and End Shift are now available from the persistent top app header and stay synced with the real active shift",
      "Full Focus toggle is now globally accessible from the persistent top app header instead of only appearing on Dashboard",
      "Full Focus header copy now avoids repeating the same momentum wording shown in operational cards",
      "Daily Start Hub added as a session/day welcome overlay when today has no shift blocks yet",
      "Optional local profile fields added for first name and phone number, editable from Settings",
      "Daily Start Hub can start a real persisted shift, dismiss to Dashboard, open Entry weekly setup, or open profile settings",
      "Dashboard Experience is stored locally and survives refresh or app reopen",
      "Shift Blocks now use the correct local target date and no longer fall back to Monday when today's date lookup fails",
      "Quick Add shift controls now create and end persisted shift blocks using the same model as Entry",
      "Entry shift blocks now support editing start time, end time, miles, and delete with confirmation",
      "Week update failures now log useful save context and avoid false success states when the request fails",
      "No Supabase schema, auth, Ask My Data, XP, exports, weather, traffic, or earnings storage changes were made",
    ],
  },
  {
    version: "5.6",
    date: "2026-05",
    title: "Shift + Hours & Pattern Intelligence",
    tags: ["new", "feature", "polish"],
    items: [
      "Manual Start Shift and End Shift controls added to Entry",
      "Shift duration tracking added inside existing week/day data with no schema migration",
      "Mileage Foundation added with manual shift miles, daily miles, and weekly miles",
      "Efficiency Snapshot added for earnings per hour, earnings per mile, and miles per hour",
      "Pattern Intelligence added to Career with strongest hours, productivity windows, and morning vs night tendencies",
      "Advanced Performance Mode unlocks hourly heatmaps and best apps by hour when enough shift data exists",
      "Simple Performance Mode keeps the experience calm and lower density by default",
      "Recovery-window language replaces dead-hour framing to preserve no-shame analytics",
      "Active shifts now persist immediately and rehydrate after refresh or app reopen until End Shift is pressed",
      "Start Shift now guards against duplicate active sessions within the same week",
      "Advanced Mode now shows a distinct Operations Snapshot with shift duration, efficiency, mileage, work blocks, and deeper unlock states",
      "No GPS, background tracking, telematics, Supabase schema changes, or automated mileage tracking were added",
    ],
  },
  {
    version: "5.5",
    date: "2026-05",
    title: "Dashboard Utility Expansion",
    tags: ["new", "feature", "polish"],
    items: [
      "Daily Command Center added to the dashboard as a compact driver utility layer",
      "Live Weather Strip added through a server-side OpenWeather Edge Function integration",
      "Live Traffic Insights added through a server-side TomTom traffic flow integration",
      "Location permission is opt-in and location data remains local-only in the browser",
      "Currency selector added to Settings with USD, EUR, GBP, CAD, MXN, COP, and ARS",
      "Regional currency/date formatting is centralized and display-only with no FX conversion",
      "Milestone share cards expanded with 100 Days Tracked and major XP level-up moments",
      "Daily Command Center polish removes extra location copy and keeps Weather/Traffic compact side by side when space allows",
      "Live Weather and Traffic refresh automatically about every 30 minutes after location is enabled",
      "Historical Day Ranking now uses the active unfinished work day so it does not jump ahead in the dashboard",
      "Ask My Data defaults unspecified timeframe questions to full history instead of the recent 16-week window",
      "Ask My Data can answer weekday lists and best/worst day rankings from tracked day totals",
      "Historical weeks can be edited from History without converting them into the active open week",
      "Weather preview reduced to two future snapshots with subtle rain, heat, and cold tinting",
      "Known limitation: weather and traffic require OPENWEATHER_API_KEY and TOMTOM_API_KEY Supabase secrets before live provider data appears",
    ],
  },
  {
    version: "5.4.2",
    date: "2026-05",
    title: "Pulse Mode + Career Titles",
    tags: ["new", "feature", "polish"],
    items: [
      "Pulse Mode added as an optional momentum-reactive visual layer",
      "Dashboard can now subtly shift visual intensity for calm, steady, streak, strong, and record-chase states",
      "Career Title Generator added to Driver Identity",
      "Career titles combine driver level, behavior, goals, records, and archetype signals",
      "Pulse Mode is stored locally and can be turned on or off from Settings",
    ],
  },
  {
    version: "5.4.1",
    date: "2026-05",
    title: "Night Drive Theme",
    tags: ["new", "polish"],
    items: [
      "Night Drive added as a fourth visual theme",
      "Cockpit-style surfaces with streetlight and dashboard accents",
      "Subtle road-lane atmosphere across the app shell",
      "Theme selector updated in Settings without changing production data behavior",
    ],
  },
  {
    version: "5.4",
    date: "2026-05",
    title: "XP + Identity System",
    tags: ["new", "feature"],
    items: [
      "Dual XP System with Consistency XP and Performance XP",
      "Driver Levels from Rookie to Streex Legend",
      "Automatic Driver Archetypes based on real behavior",
      "Historical day ranking and healthy rival snippets",
      "Ideal Week comparison built from your own best weekdays",
      "Day Off V1 keeps quiet days neutral and non-punitive",
      "Adaptive Calendar Pace and Worked-Day Pace",
      "XP ledger with idempotent event keys to avoid duplicate awards",
    ],
  },
  {
    version: "5.3B.3",
    date: "2026-05",
    title: "Ask My Data",
    tags: ["feature", "polish"],
    items: [
      "Ask My Data added as a beta assistant",
      "Scope-aware answers for recent, all-time, and seasonal questions",
      "Streaming assistant responses",
      "AI usage logging for tokens, latency, scope, and estimated cost",
      "Server-side record answers for best-week questions",
    ],
  },
  {
    version: "5.3B.2",
    date: "2026-05",
    title: "Dashboard Clarity & Data Export",
    tags: ["feature", "polish"],
    items: [
      "Dashboard semantics cleanup",
      "Adaptive Active Days logic",
      "Human-readable Active Days labels",
      "Export My Data added to Settings",
      "JSON backup export",
      "CSV earnings export",
    ],
  },
  {
    version: "5.3B",
    date: "2026-05",
    title: "Social Layer & Share Center",
    tags: ["new", "feature"],
    items: [
      "Share Center added inside Journey — a calm gallery of your shareable moments",
      "Premium share cards for weekly highlights, milestones, and career moments",
      "Monthly flex cards generated straight from your recap",
      "Weekly letter excerpts as quote-style share cards",
      "Choose Story, Square, or Wide format before exporting",
      "Copy image to clipboard where supported, plus Save and Share",
      "Legendary moments get a quiet gold treatment — no confetti, no noise",
    ],
  },
  {
    version: "5.3A.1",
    date: "2026-05",
    title: "Letters Library & Share Export",
    tags: ["new", "feature"],
    items: [
      "Letters Library — every closed week archived as a chapter",
      "Each letter tagged by emotional theme and anchored to its weekly total",
      "Letters now persist permanently — your career leaves a trace",
      "Share cards can now be saved as images or shared natively",
      "Letters surfaced inside Progress Hub for easy revisiting",
    ],
  },
  {
    version: "5.3A",
    date: "2026-05",
    title: "Narrative Core",
    tags: ["new", "feature"],
    items: [
      "Weekly Letter — a calm, personal reflection generated from your real week",
      "Expanded Journey Feed with new narrative events",
      "Three strong days, streak protection, and goal-defended moments",
      "First $200/$300 weekday milestones",
      "Share card foundation for future export & social moments",
    ],
  },
  {
    version: "5.2.1",
    date: "2026-05",
    title: "Branding, Navigation & Heatmap Polish",
    tags: ["polish"],
    items: [
      "Improved Streex branding on splash and header",
      "Cleaner 4-item bottom navigation",
      "New Progress Hub for Journey, Recap & Achievements",
      "Improved monthly heatmap contrast and hierarchy",
      "Enhanced legendary day visuals with shimmer & glow",
    ],
  },
  {
    version: "5.2",
    date: "2026-05",
    title: "Monthly Recap System",
    tags: ["new", "feature"],
    items: [
      "Monthly Recap System — a cinematic end-of-month story",
      "Monthly Heatmap with all-time best day glow",
      "Emotional month summaries and closing lines",
      "Strongest week spotlight inside each month",
      "Monthly narrative flow integrated into your Journey",
    ],
  },
  {
    version: "5.1.5",
    date: "2026-05",
    title: "Cohesion & Momentum Refinement",
    tags: ["polish", "balance"],
    items: [
      "Milestones grid now uses equal heights and auto-fills with contextual cards",
      "Removed early-day negative pacing — mornings always feel hopeful",
      "New early/mid/high state vocabulary (Fresh Start → Locked In → Monster Session)",
      "Active Momentum never feels empty — near-unlock cards keep building anticipation",
      "Fresh Chapter screen now echoes last week's wins to bridge continuity",
      "Smarter motivational logic — time-of-day aware, never punishes a normal start",
    ],
  },
  {
    version: "5.1",
    date: "2026-05",
    title: "Narrative Evolution",
    tags: ["new", "feature"],
    items: [
      "Weekly Closing Experience — chapter recap when a week ends",
      "Journey Feed — your career in a living timeline",
      "Full Changelog history with version timeline",
      "Near-momentum items keep the dashboard alive",
      "Smarter pacing — no more 'rebuilding' too early in the day",
      "Milestones now use a 2-column trophy grid on mobile",
      "Expanded Performance insights (weekday averages, weekend pace, app strength)",
      "Post-week state replaces the old onboarding screen",
    ],
  },
  {
    version: "5.0.2",
    date: "2026-05",
    title: "UX, Emotional Logic & Monthly Progression",
    tags: ["polish", "feature"],
    items: [
      "Unified mood engine — headline, pace and commentary always agree",
      "Pre-run states for $0 mornings",
      "End Day moved inside the Quick Add card",
      "Closed-day badge prevents accidental edits",
      "Monthly Progression replaces punishing growth %",
    ],
  },
  {
    version: "5.0.1",
    date: "2026-05",
    title: "Navigation Cleanup",
    tags: ["polish"],
    items: [
      "Settings moved to user menu",
      "Less crowded mobile bottom navigation",
      "Improved dashboard hierarchy",
    ],
  },
  {
    version: "5.0",
    date: "2026-04",
    title: "Career Journey & End Day",
    tags: ["feature"],
    items: [
      "Career page with archetype + lifetime stats",
      "End Day flow with rich daily recap",
      "Daily record progression psychology",
    ],
  },
  {
    version: "4.5",
    date: "2026-04",
    title: "Emotional Reward & Stability",
    tags: ["feature", "polish"],
    items: [
      "Record Celebration system with particles + haptics",
      "Advanced rotating commentary",
      "Layout stability fixes for long emotional headers",
    ],
  },
  {
    version: "4.0",
    date: "2026-03",
    title: "Smart Momentum Layer",
    tags: ["feature"],
    items: [
      "Active Momentum streak section",
      "Smart dashboard headers",
      "Daily and weekly record chases",
    ],
  },
  {
    version: "3.0",
    date: "2026-02",
    title: "Achievements & Rarity",
    tags: ["feature"],
    items: [
      "Achievements system with rarity tiers",
      "RPG mode polish",
      "Mobile day detail view",
    ],
  },
];
