export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  tags?: ("new" | "fix" | "polish" | "feature" | "balance")[];
  items: string[];
}

export const CURRENT_VERSION = "0.4.0";

export function formatVersionLabel(version: string): string {
  const normalized = version.trim().replace(/^v/i, "");
  const major = Number.parseInt(normalized.split(".")[0] ?? "", 10);
  if (major === 0) return `Beta ${normalized}`;
  if (major >= 3 && major <= 5) return `Alpha v${normalized}`;
  return `v${normalized}`;
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "0.4.0",
    date: "2026-06",
    title: "Signature — Flagship STREEX Theme",
    tags: ["new", "feature"],
    items: [
      "New Signature theme: the official STREEX flagship visual identity",
      "Premium dark surfaces with layered depth, glass-like cards, and a refined yellow accent system",
      "Cinematic header and bottom nav with quiet hairline glows and mission-control polish",
      "Subtle breathing horizon glow aligned with the animated splash and auth streak language",
      "Reduced-motion users receive a static premium treatment without breathing animations",
      "Visual layer only — auth, earnings, shifts, achievements, XP, exports, Ask My Data, and backend behavior unchanged",
    ],
  },
  {
    version: "0.3.4",
    date: "2026-06",
    title: "Premium Auth + Splash Visual Refresh",
    tags: ["polish"],
    items: [
      "Splash loading screens now use a premium dark Streex treatment with the official logo, yellow motion streaks, and subtle brand glow",
      "Login, sign up, and password reset screens now share the same dark cinematic Streex visual language",
      "Auth form behavior, Supabase session handling, protected routes, dashboard logic, earnings data, and backend architecture were not changed",
      "Reduced-motion users receive a static premium splash and auth background without moving streak animations",
    ],
  },
  {
    version: "0.3.3",
    date: "2026-06",
    title: "Daily Report Export Polish",
    tags: ["fix", "polish"],
    items: [
      "End Day Within Reach copy now points to the next daily earning milestone instead of suggesting a first milestone that may already be completed",
      "Daily Report image export now uses a richer branded report layout that mirrors the visible close-day report structure more closely",
      "Report image generation now includes daily summary, operational metrics, shift intelligence, narrative insights, and within-reach context when available",
      "No earnings calculations, shift persistence, snapshots, Ask My Data, auth, or Supabase architecture behavior changed",
    ],
  },
  {
    version: "0.3.2",
    date: "2026-06",
    title: "Full Focus Rank + Conditions Polish",
    tags: ["polish"],
    items: [
      "Full Focus main summary now replaces the redundant Shift status mini-card with same-weekday historical rank",
      "Momentum mini-card replaced with compact Conditions context using the existing live weather and traffic utility data",
      "Daily Command Center now shares the Dashboard utility controller so Full Focus conditions and utility cards stay in sync without duplicate provider calls",
      "Dashboard ordering, Standard Dashboard layout, Quick Add, earnings calculations, snapshots, Ask My Data, auth, and Supabase architecture behavior were not changed",
    ],
  },
  {
    version: "0.3.1",
    date: "2026-06",
    title: "Quick Earnings Update",
    tags: ["new", "polish"],
    items: [
      "Quick Add now opens a focused quick-update flow instead of immediately showing the full app entry form",
      "Uber and Lyft are prioritized as large one-tap update targets, with fallback support for the next available apps if needed",
      "Quick updates use current accumulated app totals, not additive deltas, so earning snapshots continue to measure real changes safely",
      "Optional miles and ride count can be updated from the quick flow when an active shift exists, without forcing ride capture",
      "More Apps preserves access to the full entry form for all apps, mileage, shift blocks, and manual logged-state controls",
      "Earnings snapshot writes now guard against duplicate same-transition inserts from rapid repeated saves",
      "Shift Intelligence timing now deduplicates identical snapshot transitions so existing duplicate rows do not inflate observed timing",
      "No stored earnings are converted, duplicated, or reinterpreted; this is a capture workflow improvement only",
    ],
  },
  {
    version: "0.3.0",
    date: "2026-06",
    title: "Work Hours, Ride Count + Daily Report Intelligence",
    tags: ["new", "feature"],
    items: [
      "Ride Count foundation added to shift blocks so rides can be captured alongside start time, end time, and miles",
      "Weekly hours goal support added as an optional commitment target separate from the weekly earnings goal",
      "Goal outcome classification added for Money Victory, Discipline Victory, Complete Victory, Elite Week, and Building Week",
      "Work Hours Intelligence expanded with hours, rides, earnings per ride, rides per hour, minutes per ride, and operational efficiency context",
      "End Day now opens a richer Daily Report with summary, performance context, weekly impact, shift intelligence, narrative insights, and export/share actions",
      "Daily Report image export uses a dedicated branded report layout instead of capturing app controls",
      "Ask My Data context now includes tracked shift hours, rides, miles, and efficiency summaries for supported hours/rides questions",
      "Added an additive migration for weekly hours goal fields; ride count is stored inside existing shift blocks, with no separate shifts table created",
      "Ride Count remains manual-first and real best earning hour remains unsupported until Streex receives individual ride timestamps",
    ],
  },
  {
    version: "0.2.3",
    date: "2026-06",
    title: "Operations Scope Clarity",
    tags: ["polish"],
    items: [
      "Career Shift Intelligence now labels its snapshot as Lifetime Operations Snapshot so historical scope is clear",
      "Dashboard now surfaces This Week Operations Snapshot for current-week hours, efficiency, miles, work blocks, active shifts, and average shift context",
      "Weekly operations reuse the existing Shift Intelligence calculation path with current-week data only",
      "Current-week earnings snapshots are filtered to the active week so Dashboard timing context does not mix career history",
      "No database schema, stored earning amounts, auth, XP, achievements, Ask My Data backend logic, exports, or Supabase project architecture behavior changed",
    ],
  },
  {
    version: "0.2.2",
    date: "2026-06",
    title: "Reward Income Classification",
    tags: ["polish", "balance"],
    items: [
      "Octopus is now treated as reward income for operational performance calculations",
      "Reward income still counts in real day totals, week totals, records, Best Day, exports, and general earnings history",
      "Shift efficiency, earnings per hour, earnings per mile, hourly timing, and app-by-hour patterns now exclude reward income so work performance is not distorted",
      "Existing Octopus history is automatically interpreted as reward income by app name; no historical data migration or manual recoding is required",
      "No database schema, stored earning amounts, auth, XP, achievements, Ask My Data backend logic, exports, or Supabase project architecture behavior changed",
    ],
  },
  {
    version: "0.2.1",
    date: "2026-06",
    title: "Late Earnings Adjustment Handling",
    tags: ["fix", "polish"],
    items: [
      "Late tips and historical earning edits now continue improving real day, week, record, efficiency, and Ask My Data totals",
      "Historical earning adjustments are excluded from observed timing patterns when the update is saved after the original work day",
      "Observed Update Hour now uses same-day earning updates only, preventing old tips from making the edit time look like a strong earning hour",
      "Estimated timing fallback remains available when there are not enough same-day earning updates",
      "No database schema, earnings storage, exports, auth, XP, achievements, Ask My Data logic, or Supabase project architecture behavior changed",
    ],
  },
  {
    version: "0.2.0",
    date: "2026-06",
    title: "Earnings Snapshots + Honest Pattern Intelligence",
    tags: ["new", "feature", "polish"],
    items: [
      "Earnings Snapshots V1 added so Streex can record lightweight earning-update deltas when app earnings change",
      "Shift Intelligence timing cards now distinguish observed earning-update patterns from shift-duration estimates",
      "Strong Hour language replaced with more honest timing labels such as Observed Update Hour and Estimated Window",
      "Hourly Heatmap now labels whether it is based on saved earnings updates or estimated from completed shift duration",
      "Career timing copy now clearly states that current timing insights are not ride-level timestamp analytics",
      "If the earnings_snapshots backend table is not deployed yet, normal week saving continues and snapshots fail gracefully",
      "No existing earnings values, exports, Ask My Data logic, auth, XP, achievements, or Supabase project architecture behavior changed",
    ],
  },
  {
    version: "0.1.2",
    date: "2026-06",
    title: "Shift Blocks Mobile Layout Fix",
    tags: ["fix", "polish"],
    items: [
      "Entry Shift Blocks now use stable mobile grids so Start and End time fields no longer overlap or spill outside the card",
      "Miles editing now sits in a balanced row with the delete action instead of being squeezed into a broken narrow column",
      "The same layout safeguard was applied to expanded weekly shift rows for narrow screens",
      "No shift calculations, persistence, earnings data, auth, Ask My Data, XP, exports, backend schema, or Supabase architecture behavior changed",
    ],
  },
  {
    version: "0.1.1",
    date: "2026-06",
    title: "Ask My Data Mobile Composer Fix",
    tags: ["fix", "polish"],
    items: [
      "Ask My Data mobile composer now stays compact and contained when the iOS/Safari keyboard opens",
      "Conversation area uses isolated scrolling with safe-area-aware composer spacing to reduce mobile overflow and layout breakage",
      "Voice input button added using browser-native speech recognition when available",
      "Unsupported voice input now fails gracefully without breaking normal text entry",
      "Copy Conversation button added for copying the current Ask My Data chat as readable plain text",
      "No Ask My Data analytics logic, auth, navigation, earnings data, backend schema, XP, exports, or Supabase architecture behavior changed",
    ],
  },
  {
    version: "0.1.0",
    date: "2026-06",
    title: "Beta Baseline",
    tags: ["polish"],
    items: [
      "Streex versioning reset for beta using public 0.x semantic versions",
      "Alpha V5.x history preserved as internal development archive instead of being discarded",
      "Current beta baseline includes Full Focus, Shift + Mileage, Ask My Data, Admin Ops, Daily Command Center, and branded PWA icon setup",
      "App version comparison now treats archived V5.x builds as Alpha history so stale Alpha version settings do not block the Beta app",
      "No dashboard, auth, earnings, shifts, analytics, XP, exports, navigation, backend schema, or Supabase architecture behavior changed",
    ],
  },
  {
    version: "5.7.9",
    date: "2026-06",
    title: "Branded PWA App Icons",
    tags: ["fix", "polish"],
    items: [
      "Branded Streex icons added for iPhone and iPad Home Screen installation",
      "Android installed PWA icons configured through a production manifest",
      "Browser favicon references now use the dedicated Streex icon asset",
      "Stable public icon URLs replace generic fallback icon behavior",
      "Existing Home Screen installations may need to be removed and added again because installed app icons are cached by the operating system",
      "No dashboard, auth, earnings, shift, analytics, XP, exports, navigation, or backend behavior changed",
    ],
  },
  {
    version: "5.7.8",
    date: "2026-06",
    title: "App Resume Persistence Audit",
    tags: ["fix", "polish"],
    items: [
      "Auth restoration now uses Supabase's initial session event without a competing session lookup",
      "Quick React remounts and app resumes retain the authenticated session instead of briefly falling back to login or replaying the splash",
      "Runtime access and version checks refresh in the background after their first successful validation",
      "Update notices now require a genuinely newer configured version instead of any version mismatch",
      "Weeks, settings, and active-shift state retain the last hydrated in-memory snapshot while backend data refreshes",
      "Authenticated pages now reuse the root user session instead of creating competing auth subscriptions",
      "Development-safe lifecycle diagnostics added for splash, auth, visibility, runtime, version, hydration, and intentional reload events",
      "No database schema, navigation, dashboard design, earnings calculations, XP, achievements, exports, or backend architecture changes were made",
    ],
  },
  {
    version: "5.7.7",
    date: "2026-06",
    title: "Ask My Data Intent Router",
    tags: ["fix", "polish"],
    items: [
      "Ask My Data now classifies question intent before choosing an answer path",
      "Hour, streak, month, goal, ranking, insight, pattern, coaching, and unsupported intents now avoid falling into day-ranking answers",
      "Strongest month, highest earning streak, current goal pace, today ranking, closest record, and combined weekend trend now have deterministic support where data is available",
      "Unsupported hourly, location, ride-type, and rival/version questions now return clearer capability-aware responses",
      "Insight and coaching prompts now return data-backed Insight, Evidence, and Opportunity style responses",
      "Ask My Data Challenge Set added for repeatable manual QA certification",
      "No database schema, auth, dashboard, XP, achievements, exports, or roadmap systems were changed",
    ],
  },
  {
    version: "5.7.6",
    date: "2026-06",
    title: "Master Consolidation Polish",
    tags: ["fix", "polish"],
    items: [
      "Dashboard generic motivation banner removed so utility flows directly into actionable record context",
      "Ask My Data mobile layout stabilized with a fixed input area and scrollable conversation region",
      "Ask My Data now calculates two consecutive days off by comparing combined weekday-pair averages",
      "Entry Shift + Mileage now separates active shift state from historical shift blocks",
      "Historical shift blocks renamed to This Week's Shifts and converted to compact expandable rows",
      "Shift edit controls rebalanced on mobile to prevent Start, End, and Miles fields from overlapping",
      "No database schema, XP, achievements, analytics model, auth, exports, or roadmap systems were changed",
    ],
  },
  {
    version: "5.7.5",
    date: "2026-06",
    title: "Admin Re-Engagement Email",
    tags: ["new", "feature"],
    items: [
      "Admin Ops now includes a manual User Re-Engagement email panel",
      "Admins can send a test email before broadcasting to users",
      "Email campaigns support test, specific user, inactive users, and all active users audiences",
      "Campaign subject, message, and app link are editable before each send",
      "APP_PUBLIC_URL can provide the default app link while the admin can still override it",
      "Email sending uses the server-side admin-email Edge Function and keeps RESEND_API_KEY out of frontend code",
      "Marketing unsubscribe support added through email_preferences and tokenized unsubscribe links",
      "Email campaigns and recipients are recorded for basic audit history",
      "No SMS, automated campaigns, dashboard, earnings, XP, Ask My Data, or exports changes were made",
    ],
  },
  {
    version: "5.7.4",
    date: "2026-06",
    title: "Admin Ops UX Hotfix",
    tags: ["fix", "polish"],
    items: [
      "Required update notices no longer block admin users from reaching Admin Ops",
      "Required update notices now explain what is happening and include a Sign Out option",
      "Admin login now has a distinct internal Admin Ops presentation and does not offer public sign-up",
      "Avatar menu feedback entry simplified to Feedback",
      "Feedback modal copy simplified and the feedback type selector now opens above the modal layer",
      "No dashboard, earnings, XP, Ask My Data, exports, or Supabase schema changes were made",
    ],
  },
  {
    version: "5.7.2",
    date: "2026-06",
    title: "Admin Ops + Feedback Inbox + App Version Control",
    tags: ["new", "feature", "polish"],
    items: [
      "Protected /admin route added for internal Streex operations",
      "Admin access foundation added with server-side validation through the admin-ops Edge Function",
      "Initial owner admin seeded for juangaudino@gmail.com through the admin_users table",
      "User management tools added for totals, recent users, inactive users, blocked users, usage stats, and account restriction actions",
      "Block/unblock support added through account_access_controls with a restricted-account screen on app load",
      "Delete user action is intentionally implemented as delete_pending soft restriction instead of destructive data deletion",
      "Force Sign Out All Users added as an app-level forced_logout_after timestamp checked during auth/runtime load",
      "App version control added with optional or required update notices and a Refresh App action",
      "Suggestions / Feedback added to the Avatar menu with suggestion, bug report, and general feedback types",
      "Admin Feedback Inbox added for filtering, reviewing, planning, resolving, dismissing, or deleting feedback",
      "No dashboard, earnings, XP, Ask My Data, exports, themes, or Supabase project architecture changes were made",
    ],
  },
  {
    version: "5.7.1",
    date: "2026-06",
    title: "Navigation Cleanup + AI Visibility Layer",
    tags: ["polish"],
    items: [
      "Ask AI is now promoted to the primary bottom navigation for stronger Ask My Data visibility",
      "Compare moved from the bottom navigation into the Progress menu",
      "History moved from the Avatar menu into the Progress menu",
      "Progress menu now groups Journey, Monthly Recap, Letters, Achievements, History, and Compare",
      "Avatar menu simplified to Settings, What's New, and Sign Out",
      "No routes, dashboard logic, auth, earnings, XP, analytics, or backend behavior were changed",
    ],
  },
  {
    version: "5.7",
    date: "2026-05",
    title: "Full Focus Dashboard",
    tags: ["new", "feature", "polish"],
    items: [
      "Full Focus Dashboard Experience added as an operational mode separate from themes",
      "Settings now includes Dashboard Experience with Standard and Full Focus options",
      "Dashboard includes a compact quick toggle for switching between Standard and Full Focus",
      "Full Focus prioritizes current earnings, same-day average comparison, goal progress, shift state, momentum, and Quick Add",
      "Weather, traffic, historical day context, and momentum remain available as calmer secondary operational context",
      "Driver Identity, achievements, milestones, and longer reflection systems stay in Standard instead of dominating Full Focus",
      "Header and navigation quiet slightly in Full Focus to reclaim vertical space",
      "Dashboard mode toggle now lives in the top app header near Progress and Profile controls with the current mode clearly visible",
      "Full Focus now uses a tighter driver-console layout with Quick Add immediately after the cockpit summary",
      "Daily Command Center renders as a compact utility strip in Full Focus so live utility no longer dominates the top of the dashboard",
      "Start Shift and End Shift are now available from the persistent top app header and stay synced with the real active shift",
      "Full Focus toggle is now globally accessible from the persistent top app header instead of only appearing on Dashboard",
      "Full Focus header copy now avoids repeating the same momentum wording shown in operational cards",
      "Daily Start Hub added as a session/day welcome overlay when today has no shift blocks yet",
      "Optional local profile fields added for first name and phone number, editable from Settings",
      "Daily Start Hub can start a real persisted shift, dismiss to Dashboard, open Entry weekly setup, or open profile settings",
      "Dashboard Experience is stored locally and survives refresh or app reopen",
      "Shift Blocks now use the correct local target date and no longer fall back to Monday when today's date lookup fails",
      "Quick Add shift controls now create and end persisted shift blocks using the same model as Entry",
      "Entry shift blocks now support editing start time, end time, miles, and delete with confirmation",
      "Week update failures now log useful save context and avoid false success states when the request fails",
      "No Supabase schema, auth, Ask My Data, XP, exports, weather, traffic, or earnings storage changes were made",
    ],
  },
  {
    version: "5.6",
    date: "2026-05",
    title: "Shift + Hours & Pattern Intelligence",
    tags: ["new", "feature", "polish"],
    items: [
      "Manual Start Shift and End Shift controls added to Entry",
      "Shift duration tracking added inside existing week/day data with no schema migration",
      "Mileage Foundation added with manual shift miles, daily miles, and weekly miles",
      "Efficiency Snapshot added for earnings per hour, earnings per mile, and miles per hour",
      "Pattern Intelligence added to Career with strongest hours, productivity windows, and morning vs night tendencies",
      "Advanced Performance Mode unlocks hourly heatmaps and best apps by hour when enough shift data exists",
      "Simple Performance Mode keeps the experience calm and lower density by default",
      "Recovery-window language replaces dead-hour framing to preserve no-shame analytics",
      "Active shifts now persist immediately and rehydrate after refresh or app reopen until End Shift is pressed",
      "Start Shift now guards against duplicate active sessions within the same week",
      "Advanced Mode now shows a distinct Operations Snapshot with shift duration, efficiency, mileage, work blocks, and deeper unlock states",
      "No GPS, background tracking, telematics, Supabase schema changes, or automated mileage tracking were added",
    ],
  },
  {
    version: "5.5",
    date: "2026-05",
    title: "Dashboard Utility Expansion",
    tags: ["new", "feature", "polish"],
    items: [
      "Daily Command Center added to the dashboard as a compact driver utility layer",
      "Live Weather Strip added through a server-side OpenWeather Edge Function integration",
      "Live Traffic Insights added through a server-side TomTom traffic flow integration",
      "Location permission is opt-in and location data remains local-only in the browser",
      "Currency selector added to Settings with USD, EUR, GBP, CAD, MXN, COP, and ARS",
      "Regional currency/date formatting is centralized and display-only with no FX conversion",
      "Milestone share cards expanded with 100 Days Tracked and major XP level-up moments",
      "Daily Command Center polish removes extra location copy and keeps Weather/Traffic compact side by side when space allows",
      "Live Weather and Traffic refresh automatically about every 30 minutes after location is enabled",
      "Historical Day Ranking now uses the active unfinished work day so it does not jump ahead in the dashboard",
      "Ask My Data defaults unspecified timeframe questions to full history instead of the recent 16-week window",
      "Ask My Data can answer weekday lists and best/worst day rankings from tracked day totals",
      "Historical weeks can be edited from History without converting them into the active open week",
      "Weather preview reduced to two future snapshots with subtle rain, heat, and cold tinting",
      "Known limitation: weather and traffic require OPENWEATHER_API_KEY and TOMTOM_API_KEY Supabase secrets before live provider data appears",
    ],
  },
  {
    version: "5.4.2",
    date: "2026-05",
    title: "Pulse Mode + Career Titles",
    tags: ["new", "feature", "polish"],
    items: [
      "Pulse Mode added as an optional momentum-reactive visual layer",
      "Dashboard can now subtly shift visual intensity for calm, steady, streak, strong, and record-chase states",
      "Career Title Generator added to Driver Identity",
      "Career titles combine driver level, behavior, goals, records, and archetype signals",
      "Pulse Mode is stored locally and can be turned on or off from Settings",
    ],
  },
  {
    version: "5.4.1",
    date: "2026-05",
    title: "Night Drive Theme",
    tags: ["new", "polish"],
    items: [
      "Night Drive added as a fourth visual theme",
      "Cockpit-style surfaces with streetlight and dashboard accents",
      "Subtle road-lane atmosphere across the app shell",
      "Theme selector updated in Settings without changing production data behavior",
    ],
  },
  {
    version: "5.4",
    date: "2026-05",
    title: "XP + Identity System",
    tags: ["new", "feature"],
    items: [
      "Dual XP System with Consistency XP and Performance XP",
      "Driver Levels from Rookie to Streex Legend",
      "Automatic Driver Archetypes based on real behavior",
      "Historical day ranking and healthy rival snippets",
      "Ideal Week comparison built from your own best weekdays",
      "Day Off V1 keeps quiet days neutral and non-punitive",
      "Adaptive Calendar Pace and Worked-Day Pace",
      "XP ledger with idempotent event keys to avoid duplicate awards",
    ],
  },
  {
    version: "5.3B.3",
    date: "2026-05",
    title: "Ask My Data",
    tags: ["feature", "polish"],
    items: [
      "Ask My Data added as a beta assistant",
      "Scope-aware answers for recent, all-time, and seasonal questions",
      "Streaming assistant responses",
      "AI usage logging for tokens, latency, scope, and estimated cost",
      "Server-side record answers for best-week questions",
    ],
  },
  {
    version: "5.3B.2",
    date: "2026-05",
    title: "Dashboard Clarity & Data Export",
    tags: ["feature", "polish"],
    items: [
      "Dashboard semantics cleanup",
      "Adaptive Active Days logic",
      "Human-readable Active Days labels",
      "Export My Data added to Settings",
      "JSON backup export",
      "CSV earnings export",
    ],
  },
  {
    version: "5.3B",
    date: "2026-05",
    title: "Social Layer & Share Center",
    tags: ["new", "feature"],
    items: [
      "Share Center added inside Journey — a calm gallery of your shareable moments",
      "Premium share cards for weekly highlights, milestones, and career moments",
      "Monthly flex cards generated straight from your recap",
      "Weekly letter excerpts as quote-style share cards",
      "Choose Story, Square, or Wide format before exporting",
      "Copy image to clipboard where supported, plus Save and Share",
      "Legendary moments get a quiet gold treatment — no confetti, no noise",
    ],
  },
  {
    version: "5.3A.1",
    date: "2026-05",
    title: "Letters Library & Share Export",
    tags: ["new", "feature"],
    items: [
      "Letters Library — every closed week archived as a chapter",
      "Each letter tagged by emotional theme and anchored to its weekly total",
      "Letters now persist permanently — your career leaves a trace",
      "Share cards can now be saved as images or shared natively",
      "Letters surfaced inside Progress Hub for easy revisiting",
    ],
  },
  {
    version: "5.3A",
    date: "2026-05",
    title: "Narrative Core",
    tags: ["new", "feature"],
    items: [
      "Weekly Letter — a calm, personal reflection generated from your real week",
      "Expanded Journey Feed with new narrative events",
      "Three strong days, streak protection, and goal-defended moments",
      "First $200/$300 weekday milestones",
      "Share card foundation for future export & social moments",
    ],
  },
  {
    version: "5.2.1",
    date: "2026-05",
    title: "Branding, Navigation & Heatmap Polish",
    tags: ["polish"],
    items: [
      "Improved Streex branding on splash and header",
      "Cleaner 4-item bottom navigation",
      "New Progress Hub for Journey, Recap & Achievements",
      "Improved monthly heatmap contrast and hierarchy",
      "Enhanced legendary day visuals with shimmer & glow",
    ],
  },
  {
    version: "5.2",
    date: "2026-05",
    title: "Monthly Recap System",
    tags: ["new", "feature"],
    items: [
      "Monthly Recap System — a cinematic end-of-month story",
      "Monthly Heatmap with all-time best day glow",
      "Emotional month summaries and closing lines",
      "Strongest week spotlight inside each month",
      "Monthly narrative flow integrated into your Journey",
    ],
  },
  {
    version: "5.1.5",
    date: "2026-05",
    title: "Cohesion & Momentum Refinement",
    tags: ["polish", "balance"],
    items: [
      "Milestones grid now uses equal heights and auto-fills with contextual cards",
      "Removed early-day negative pacing — mornings always feel hopeful",
      "New early/mid/high state vocabulary (Fresh Start → Locked In → Monster Session)",
      "Active Momentum never feels empty — near-unlock cards keep building anticipation",
      "Fresh Chapter screen now echoes last week's wins to bridge continuity",
      "Smarter motivational logic — time-of-day aware, never punishes a normal start",
    ],
  },
  {
    version: "5.1",
    date: "2026-05",
    title: "Narrative Evolution",
    tags: ["new", "feature"],
    items: [
      "Weekly Closing Experience — chapter recap when a week ends",
      "Journey Feed — your career in a living timeline",
      "Full Changelog history with version timeline",
      "Near-momentum items keep the dashboard alive",
      "Smarter pacing — no more 'rebuilding' too early in the day",
      "Milestones now use a 2-column trophy grid on mobile",
      "Expanded Performance insights (weekday averages, weekend pace, app strength)",
      "Post-week state replaces the old onboarding screen",
    ],
  },
  {
    version: "5.0.2",
    date: "2026-05",
    title: "UX, Emotional Logic & Monthly Progression",
    tags: ["polish", "feature"],
    items: [
      "Unified mood engine — headline, pace and commentary always agree",
      "Pre-run states for $0 mornings",
      "End Day moved inside the Quick Add card",
      "Closed-day badge prevents accidental edits",
      "Monthly Progression replaces punishing growth %",
    ],
  },
  {
    version: "5.0.1",
    date: "2026-05",
    title: "Navigation Cleanup",
    tags: ["polish"],
    items: [
      "Settings moved to user menu",
      "Less crowded mobile bottom navigation",
      "Improved dashboard hierarchy",
    ],
  },
  {
    version: "5.0",
    date: "2026-04",
    title: "Career Journey & End Day",
    tags: ["feature"],
    items: [
      "Career page with archetype + lifetime stats",
      "End Day flow with rich daily recap",
      "Daily record progression psychology",
    ],
  },
  {
    version: "4.5",
    date: "2026-04",
    title: "Emotional Reward & Stability",
    tags: ["feature", "polish"],
    items: [
      "Record Celebration system with particles + haptics",
      "Advanced rotating commentary",
      "Layout stability fixes for long emotional headers",
    ],
  },
  {
    version: "4.0",
    date: "2026-03",
    title: "Smart Momentum Layer",
    tags: ["feature"],
    items: [
      "Active Momentum streak section",
      "Smart dashboard headers",
      "Daily and weekly record chases",
    ],
  },
  {
    version: "3.0",
    date: "2026-02",
    title: "Achievements & Rarity",
    tags: ["feature"],
    items: [
      "Achievements system with rarity tiers",
      "RPG mode polish",
      "Mobile day detail view",
    ],
  },
];
