import { useState } from "react";
import { Activity, BookOpen, Clock3 } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { OperationalExplorerData, OperationalExplorerFilters, OperationalWindowPreset } from "@/lib/operationalExplorer";
import { formatCurrency } from "@/lib/store";
import DriverPlaybookModal, { type DriverPlaybookData } from "./DriverPlaybookModal";

const WINDOWS: Array<[OperationalWindowPreset, string]> = [["all", "All worked hours"], ["morning", "Morning"], ["afternoon", "Afternoon"], ["evening", "Evening"], ["late-night", "Late night"], ["custom", "Custom"]];

export default function OperationalExplorerPanel({ data, filters, onChange, playbook }: { data: OperationalExplorerData; filters: OperationalExplorerFilters; onChange: (next: OperationalExplorerFilters) => void; playbook: Omit<DriverPlaybookData, "operational"> }) {
  const [playbookOpen, setPlaybookOpen] = useState(false);
  const validHourly = data.hourly.filter((row) => row.hours > 0);
  const maxHeatRate = Math.max(1, ...data.heatmap.flatMap((day) => day.hours.map((hour) => hour.rate ?? 0)));
  const metric = (value: number | null, suffix = "") => value == null ? "—" : `${value.toFixed(2)}${suffix}`;
  return <section className="rounded-3xl border border-[#E6CE20]/25 bg-card/85 p-5 shadow-xl backdrop-blur lg:p-7">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-[#B9A400]">Beta 0.9.4</p><h2 className="mt-2 text-2xl font-black">Operational Explorer</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Exact worked-time overlap with clearly labeled observed or estimated production. Rewards stay outside efficiency.</p></div><button onClick={() => setPlaybookOpen(true)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#E6CE20] px-5 text-sm font-black text-black"><BookOpen className="h-4 w-4" />Create Driver Playbook</button></div>
    <div className="mt-5 grid gap-3 rounded-2xl border border-border bg-background/50 p-4 md:grid-cols-[1fr_auto_auto]">
      <label className="grid gap-1 text-[10px] font-black uppercase tracking-widest text-muted-foreground">Time window<select className="h-10 rounded-xl border border-border bg-background px-3 text-sm text-foreground" value={filters.windowPreset} onChange={(event) => onChange({ ...filters, windowPreset: event.target.value as OperationalWindowPreset })}>{WINDOWS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      {filters.windowPreset === "custom" && <><label className="grid gap-1 text-[10px] font-black uppercase tracking-widest text-muted-foreground">From<input type="time" step="900" value={filters.windowStart ?? "09:00"} onChange={(event) => onChange({ ...filters, windowStart: event.target.value })} className="h-10 rounded-xl border border-border bg-background px-3 text-foreground" /></label><label className="grid gap-1 text-[10px] font-black uppercase tracking-widest text-muted-foreground">To<input type="time" step="900" value={filters.windowEnd ?? "17:00"} onChange={(event) => onChange({ ...filters, windowEnd: event.target.value })} className="h-10 rounded-xl border border-border bg-background px-3 text-foreground" /></label></>}
    </div>
    <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-border px-3 py-1 font-bold">{data.source}</span><span className="rounded-full border border-border px-3 py-1 font-bold">{data.sampleLabel}</span><span className="rounded-full border border-border px-3 py-1">{data.totals.days} days · {data.totals.shifts} shifts · {data.totals.hours.toFixed(1)}h</span>{data.coverage > 0 && <span className="rounded-full border border-border px-3 py-1">{data.coverage.toFixed(0)}% timestamp-observed</span>}</div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[
      ["Earnings / hour", data.totals.earningsPerHour == null ? "—" : `${formatCurrency(data.totals.earningsPerHour, playbook.currencySymbol)}/hr`], ["Rides / hour", metric(data.totals.ridesPerHour)], ["Miles / hour", metric(data.totals.milesPerHour)], ["Earnings / mile", data.totals.earningsPerMile == null ? "—" : `${formatCurrency(data.totals.earningsPerMile, playbook.currencySymbol)}/mi`], ["Minutes / ride", metric(data.totals.minutesPerRide)],
    ].map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-background/55 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">{label}</p><p className="mt-2 font-mono text-xl font-black">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-border p-4"><div className="mb-4 flex items-center gap-2"><Activity className="h-4 w-4 text-[#B9A400]" /><h3 className="font-black">Hourly profile</h3></div>{validHourly.length ? <div className="h-[290px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={validHourly}><CartesianGrid stroke="currentColor" opacity={0.08} vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} /><YAxis tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="earningsPerHour" name="Earnings / hour" fill="#E6CE20" radius={[7, 7, 2, 2]} /></BarChart></ResponsiveContainer></div> : <div className="grid h-[290px] place-items-center text-sm text-muted-foreground">No matching worked hours.</div>}</div>
      <div className="rounded-2xl border border-border p-4"><div className="mb-4 flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#B9A400]" /><h3 className="font-black">Best windows</h3></div><div className="space-y-2">{data.bestWindows.map((row, index) => <div key={row.hour} className="flex items-center justify-between rounded-xl bg-muted/45 p-3"><div><p className="text-sm font-bold">#{index + 1} · {row.label}</p><p className="text-[11px] text-muted-foreground">{row.hours.toFixed(1)}h · {row.source}</p></div><p className="font-mono text-sm font-black">{row.earningsPerHour == null ? "—" : `${formatCurrency(row.earningsPerHour, playbook.currencySymbol)}/hr`}</p></div>)}</div></div></div>
    <div className="mt-5 overflow-x-auto rounded-2xl border border-border p-4"><h3 className="font-black">Weekday × hour heatmap</h3><p className="mt-1 text-xs text-muted-foreground">Darker cells represent stronger weighted earnings per worked hour. Empty cells have less than 0.5 tracked hours.</p><div className="mt-4 min-w-[900px] space-y-1.5"><div className="grid grid-cols-[76px_repeat(24,minmax(28px,1fr))] gap-1 text-center text-[9px] text-muted-foreground"><span />{Array.from({ length: 24 }, (_, hour) => <span key={hour}>{hour}</span>)}</div>{data.heatmap.map((day) => <div key={day.dayName} className="grid grid-cols-[76px_repeat(24,minmax(28px,1fr))] gap-1"><span className="self-center text-xs font-bold">{day.dayName.slice(0, 3)}</span>{day.hours.map((cell) => <div key={cell.hour} title={`${day.dayName} ${cell.hour}:00 · ${cell.rate == null ? "insufficient" : `${formatCurrency(cell.rate, playbook.currencySymbol)}/hr`} · ${cell.hours.toFixed(1)}h`} className="h-8 rounded-md border border-border/50" style={{ backgroundColor: cell.rate == null ? "transparent" : `rgba(230,206,32,${0.15 + (cell.rate / maxHeatRate) * 0.85})` }} />)}</div>)}</div></div>
    <div className="mt-5 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[640px] text-sm"><thead className="bg-muted/45 text-left text-[10px] uppercase tracking-widest text-muted-foreground"><tr><th className="p-3">Weekday</th><th className="p-3">Sample days</th><th className="p-3">Hours</th><th className="p-3">Earnings / hour</th></tr></thead><tbody>{data.weekdays.map((row) => <tr key={row.dayName} className="border-t border-border"><td className="p-3 font-bold">{row.dayName}</td><td className="p-3">{row.days}</td><td className="p-3 font-mono">{row.hours.toFixed(1)}</td><td className="p-3 font-mono font-bold">{row.rate == null ? "—" : `${formatCurrency(row.rate, playbook.currencySymbol)}/hr`}</td></tr>)}</tbody></table></div>
    {playbookOpen && <DriverPlaybookModal data={{ ...playbook, operational: data }} onClose={() => setPlaybookOpen(false)} />}
  </section>;
}
