import type { WeekRecord, AppSettings, EarningsSnapshot, OperationalSnapshot, OperationalSnapshotDraft, EarningsAttribution, EarningsAttributionIntent, RideCaptureResult, RideEvent, RidePayment, RideSnapshotAllocation, RideSnapshotAllocationDraft, RideUpdateBatch, RideUpdateBatchEvent, ZoneLabel } from "@/lib/types";
import type { WeekRevision } from "@/lib/weekRevisions";
import type { User } from "@supabase/supabase-js";

export interface StoreContext {
  user: User | null;
  weeks: WeekRecord[];
  openWeek: WeekRecord | null;
  settings: AppSettings;
  earningsSnapshots: EarningsSnapshot[];
  operationalSnapshots: OperationalSnapshot[];
  earningsAttributions: EarningsAttribution[];
  rideEvents: RideEvent[];
  rideUpdateBatches: RideUpdateBatch[];
  rideUpdateBatchEvents: RideUpdateBatchEvent[];
  ridePayments: RidePayment[];
  rideSnapshotAllocations: RideSnapshotAllocation[];
  zoneLabels: ZoneLabel[];
  loading: boolean;
  hasLocalData: boolean;
  addWeek: (w: WeekRecord) => Promise<boolean>;
  updateWeek: (w: WeekRecord, attributionIntents?: EarningsAttributionIntent[], options?: { recordSnapshots?: boolean; onSnapshotsRecorded?: (snapshots: EarningsSnapshot[]) => Promise<void> | void }) => Promise<boolean>;
  recordOperationalSnapshot: (draft: OperationalSnapshotDraft) => Promise<boolean>;
  startRideEvent: (draft: { weekId: string; dayDate: string; shiftId?: string | null; app?: string | null; startedAt: string; capture: RideCaptureResult; source?: "foreground_browser" | "manual_after_shift" }) => Promise<RideEvent | null>;
  finishRideEvent: (id: string, endedAt: string, capture: RideCaptureResult) => Promise<RideEvent | null>;
  linkRideEvents: (draft: { app: string; earningsSnapshotId: string; operationalEventKey?: string | null; rideEventIds: string[] }) => Promise<boolean>;
  recordRidePayment: (draft: { rideEventId: string; earningsSnapshotId: string; kind: "manual_base" | "late_tip" | "adjustment"; observedAt: string }) => Promise<boolean>;
  replaceSnapshotAllocations: (snapshotId: string, allocations: RideSnapshotAllocationDraft[]) => Promise<boolean>;
  saveZoneLabel: (draft: { zoneKey: string; label: string; source?: "user" | "suggested" }) => Promise<boolean>;
  saveEarningsAttribution: (snapshotId: string, intent: Omit<EarningsAttributionIntent, "dayDate" | "app" | "previousAmount" | "newAmount">) => Promise<boolean>;
  deleteWeek: (id: string) => void;
  updateSettings: (s: AppSettings) => Promise<boolean>;
  importLocalData: () => Promise<number | undefined>;
  reload: () => void;
  syncStatus: "saved" | "saving" | "conflict" | "error";
  hasPendingConflict: boolean;
  resolveWeekConflict: (strategy: "keep-remote" | "use-local") => Promise<boolean>;
  retryLastSave: () => Promise<boolean>;
  getWeekRevisions: (weekId: string) => Promise<WeekRevision[]>;
  restoreRevision: (weekId: string, revisionId: string) => Promise<boolean>;
}
